name: Publish to GitHub Registry

on: # Enable push when in new installation
  push:
    branches:
      - php7.4-v1

jobs:
  push:
    runs-on: ubuntu-latest

    env:
      VERSION: 1.${{ github.run_number }}
      REPO: ${{ github.event.repository.name }}
      IMAGE: ghcr.io/${{github.event.repository.owner.name}}/${{ github.event.repository.name }}

    steps:
      - uses: actions/checkout@v2

      - name: Push to GitHub Container Registry
        run: |
          echo ${{github.token}} | docker login ghcr.io --username ${{github.event.repository.owner.name}} --password-stdin
          docker build -t ${{ env.IMAGE }}:$(echo ${GITHUB_REF##*/}) .
          docker push ${{ env.IMAGE }}:$(echo ${GITHUB_REF##*/})
